### ISSUE TITLE
Cannot open tractor-sdss-synth.py

### ISSUE THREAD

**Issue by dampach** [dstndstn/tractor#102]
I just installed tractor and tried to open the example (tractor-sdss-synth.py
), but I get this error:
```
Traceback (most recent call last):
  File "test_tractor.py", line 8, in <module>
    from tractor import *
  File "/home/dampach/.local/lib/python3.7/site-packages/tractor/__init__.py", line 1, in <module>
    from .engine import *
  File "/home/dampach/.local/lib/python3.7/site-packages/tractor/engine.py", line 18, in <module>
    from tractor.utils import MultiParams, _isint, get_class_from_name
ImportError: cannot import name 'MultiParams' from 'tractor.utils' (/home/dampach/.local/lib/python3.7/site-packages/tractor/utils/__init__.py)
```

**Comment by dstndstn** [comment]
Can you please list all the commands you ran before this happened.  Did you install it?  Or are you running from a git checkout of the code?  Because that error is coming from an installed version, but I still don't see what the problem is.

**Comment by dstndstn** [comment]
That's reasonable... and then what's the python command you're running to run that test?

**Comment by dampach** [comment]
```
python examples/tractor-sdss-synth.py
```
just like the README.md says

**Comment by dstndstn** [comment]
Okay... I asked because the stack trace you sent above it starts with
```
Traceback (most recent call last):
  File "test_tractor.py", line 8, in <module>
    from tractor import *
```

Wait, something is weird.

It says it's trying to read from
/home/dampach/.local/lib/python3.7/site-packages/tractor/utils/__init__.py

but there's... no such file in the tractor repository.  There's a `tractor/utils.py`, but not a `tractor/utils` directory.  Are you sure that that `/home/dampach/.local/lib/python3.7/site-packages/tractor` directory isn't from an old installation or something?

**Comment by dampach** [comment]
Yeah, Im sure it's not an old installation because I just started with Tractor. I just realized there is a folder named **utils** that have an  empty ``` __init__.py```  file. Maybe that´s why?

**Comment by dstndstn** [comment]
Exactly, that's the problem, but where did it come from?

**Comment by dampach** [comment]
I just don´t know xd. But I tried changing the name of this ```utils``` folder and looks like that was the problem, because now I get an error from ```astrometry```

**Comment by dstndstn** [comment]
Hooray, a different error :)
